# Generated by ChatGPT for Math Fortress
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        # Встроенные зависимости для AbstractUser
    ]

    operations = [
        # Пользователь (кастомный)
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], default='STUDENT', max_length=16)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={'abstract': False,},
        ),

        # Classroom
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(help_text='Код-приглашение для присоединения к классу', max_length=12, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),

        # ClassMembership
        migrations.CreateModel(
            name='ClassMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('classroom', 'student')},
            },
        ),

        # Team
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='api.classroom')),
            ],
            options={
                'unique_together': {('classroom', 'name')},
            },
        ),

        # TeamMembership
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role_in_team', models.CharField(choices=[('MEMBER', 'Member'), ('CAPTAIN', 'Captain')], default='MEMBER', max_length=16)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.team')),
            ],
            options={
                'unique_together': {('team', 'student')},
            },
        ),

        # Task
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body_md', models.TextField()),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], default='MEDIUM', max_length=16)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('max_points', models.PositiveIntegerField(default=10)),
                ('expected_answer', models.CharField(blank=True, help_text='Простой правильный ответ (опционально)', max_length=255)),
                ('solution_spec', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),

        # Assignment
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='given_assignments', to=settings.AUTH_USER_MODEL)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.classroom')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.team')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='api.task')),
            ],
        ),

        # Submission
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('answer_payload', models.JSONField(default=dict)),
                ('attempt_no', models.PositiveIntegerField(default=1)),
                ('is_correct', models.BooleanField(default=False)),
                ('feedback', models.TextField(blank=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='api.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['assignment', 'student'], name='api_submiss_assignm_abc123_idx'),
        ),

        # Score
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_points', models.IntegerField(default=0)),
                ('last_update', models.DateTimeField(default=django.utils.timezone.now)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.team')),
            ],
            options={
                'unique_together': {('student', 'classroom', 'team')},
            },
        ),
    ]
